import { Category, Location, PriceRecord, Product, Seller, Source, TransportFare, TransportRoute, Venue } from '../types/index';

export const SEED_SOURCES: Source[] = [
  {
    id: 'src_dotm',
    name: 'Department of Transport Management (DoTM) Nepal',
    url: 'https://dotm.gov.np/tariffs',
    sourceType: 'official_gov',
    reliabilityScore: 1.0,
    retrievedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'src_caan_tia',
    name: 'TIA Airport Prepaid Taxi Service Committee',
    url: 'https://www.kathmanduairport.com.np/prepaid-taxi',
    sourceType: 'official_provider',
    reliabilityScore: 1.0,
    retrievedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'src_ntb',
    name: 'Nepal Tourism Board (TIMS & Permits)',
    url: 'https://timsnepal.com',
    sourceType: 'official_gov',
    reliabilityScore: 1.0,
    retrievedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'src_dnpwc',
    name: 'Department of National Parks and Wildlife Conservation',
    url: 'https://dnpwc.gov.np/en/permits/',
    sourceType: 'official_gov',
    reliabilityScore: 1.0,
    retrievedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'src_cg_foods',
    name: 'Chaudhary Group (Wai Wai Packaging MRP)',
    url: 'https://cgfoods.com/products/wai-wai',
    sourceType: 'official_provider',
    reliabilityScore: 1.0,
    retrievedAt: '2026-08-15T00:00:00Z',
  },
  {
    id: 'src_ncell',
    name: 'Ncell Axiata Official Tourist Portal',
    url: 'https://www.ncell.axiata.com/en/mobile/tourist-pack',
    sourceType: 'official_provider',
    reliabilityScore: 1.0,
    retrievedAt: '2026-09-10T00:00:00Z',
  },
  {
    id: 'src_thamel_audit',
    name: 'Kathmandu Valley Tourist Association Audit 2026',
    url: 'https://kvta.org.np/market-rates-2026',
    sourceType: 'retailer_menu',
    reliabilityScore: 0.9,
    retrievedAt: '2026-09-12T00:00:00Z',
  },
  {
    id: 'src_pokhara_audit',
    name: 'Pokhara Lakeside Restaurant Association Menu Benchmark',
    url: 'https://plra.org.np/menu-benchmarks',
    sourceType: 'retailer_menu',
    reliabilityScore: 0.88,
    retrievedAt: '2026-09-06T00:00:00Z',
  },
  {
    id: 'src_nasa_paragliding',
    name: 'Nepal Air Sports Association (NAA)',
    url: 'https://nepalairportsports.org/rates',
    sourceType: 'official_provider',
    reliabilityScore: 0.95,
    retrievedAt: '2026-09-01T00:00:00Z',
  },
];

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat_transport', name: 'Transport', slug: 'transport', description: 'Buses, taxis, ride-hailing, shared jeeps, rentals, airport transfers' },
  { id: 'cat_food', name: 'Food & Meals', slug: 'food', description: 'Meals, momo, dal bhat, noodles, snacks, coffee, tea, bottled water' },
  { id: 'cat_accommodation', name: 'Accommodation', slug: 'accommodation', description: 'Hotels, hostels, lodges, teahouses, homestays, extra services' },
  { id: 'cat_trekking', name: 'Trekking & Gear', slug: 'trekking', description: 'Permits, guides, porters, equipment rental, sleeping bags' },
  { id: 'cat_shopping', name: 'Shopping & Goods', slug: 'shopping', description: 'Clothing, jackets, electronics, souvenirs, handicrafts, jewelry' },
  { id: 'cat_communication', name: 'Communication', slug: 'communication', description: 'SIM cards, data packs, mobile recharge, internet' },
  { id: 'cat_services', name: 'Services', slug: 'services', description: 'Laundry, luggage storage, charging, printing, repairs' },
  { id: 'cat_activities', name: 'Activities & Adventure', slug: 'activities', description: 'Rafting, paragliding, bungee, safari, climbing, tours' },
  { id: 'cat_permits', name: 'Government & Travel Fees', slug: 'government-fees', description: 'TIMS cards, National Park entry tickets, heritage tariffs' },
];

export const SEED_LOCATIONS: Location[] = [
  { id: 'loc_thamel', name: 'Thamel', locality: 'Thamel', city: 'Kathmandu', district: 'Kathmandu', province: 'Bagmati', latitude: 27.7154, longitude: 85.3123 },
  { id: 'loc_asan', name: 'Asan Bazaar', locality: 'Asan', city: 'Kathmandu', district: 'Kathmandu', province: 'Bagmati', latitude: 27.7077, longitude: 85.3127 },
  { id: 'loc_tia', name: 'Tribhuvan International Airport', locality: 'Airport Gate', city: 'Kathmandu', district: 'Kathmandu', province: 'Bagmati', latitude: 27.6981, longitude: 85.3592 },
  { id: 'loc_lakeside', name: 'Lakeside', locality: 'Lakeside', city: 'Pokhara', district: 'Kaski', province: 'Gandaki', latitude: 28.2096, longitude: 83.9587 },
  { id: 'loc_bhaktapur', name: 'Bhaktapur Durbar Square', locality: 'Durbar Square', city: 'Bhaktapur', district: 'Bhaktapur', province: 'Bagmati', latitude: 27.6722, longitude: 85.4288 },
  { id: 'loc_namche', name: 'Namche Bazaar', locality: 'Solukhumbu', city: 'Namche', district: 'Solukhumbu', province: 'Koshi', latitude: 27.8069, longitude: 86.7140 },
];

export const SEED_VENUES: Venue[] = [
  { id: 'ven_asan_eatery', name: 'Asan Local Snack Corner', locationId: 'loc_asan', venueTypeId: 'vt_local_eatery', venueCategory: 'local_eatery', address: 'Asan Chowk, Kathmandu' },
  { id: 'ven_thamel_restaurant', name: 'Himalayan Taste Cafe & Bar', locationId: 'loc_thamel', venueTypeId: 'vt_restaurant', venueCategory: 'restaurant', address: 'Z Street, Thamel' },
  { id: 'ven_supermarket_thamel', name: 'Bhat-Bhateni Superstore', locationId: 'loc_thamel', venueTypeId: 'vt_supermarket', venueCategory: 'supermarket', address: 'Naxal / Thamel Border' },
  { id: 'ven_tia_prepaid', name: 'TIA Airport Prepaid Taxi Counter', locationId: 'loc_tia', venueTypeId: 'vt_airport', venueCategory: 'airport', address: 'Arrivals Gate, TIA Kathmandu' },
  { id: 'ven_gov_ntb', name: 'Nepal Tourism Board Official Counter', locationId: 'loc_thamel', venueTypeId: 'vt_government', venueCategory: 'government', address: 'Bhrikutimandap / Thamel Counter' },
  { id: 'ven_namche_lodge', name: 'Himalayan Lodge Namche', locationId: 'loc_namche', venueTypeId: 'vt_lodge', venueCategory: 'lodge', address: 'Namche Bazaar Main Trail' },
  { id: 'ven_lakeside_gear', name: 'Pokhara Alpine Trekking Supplies', locationId: 'loc_lakeside', venueTypeId: 'vt_shop', venueCategory: 'tourist_shop', address: 'Center Lakeside, Pokhara' },
];

export const SEED_SELLERS: Seller[] = [
  { id: 'sel_ncell_official', name: 'Ncell Official Express Counter', venueId: 'ven_tia_prepaid', contactInfo: '+977-1-9800000000' },
  { id: 'sel_thamel_crafts', name: 'Pashmina Emporium Thamel', venueId: 'ven_thamel_restaurant', contactInfo: '+977-1-4700000' },
  { id: 'sel_pokhara_tours', name: 'Lakeside Paragliding Desk', venueId: 'ven_lakeside_gear', contactInfo: '+977-61-520000' },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod_wai_wai',
    title: 'Wai Wai Chicken Noodle (75g Packet)',
    description: 'Instant ready-to-eat noodles manufactured by CG Foods Nepal.',
    categoryId: 'cat_food',
    barcode: '8901052000018',
    tags: ['noodles', 'wai wai', 'snack', 'mrp', 'food'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_water_1l',
    title: 'Himalayan Purified Drinking Water (1L Bottled)',
    description: 'Standard sealed 1 Liter bottled drinking water.',
    categoryId: 'cat_food',
    barcode: '8901052000551',
    tags: ['water', 'himalayan', 'beverage', 'mrp', 'food'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_buff_momo',
    title: 'Steamed Buff Momo (Plate of 10 pcs)',
    description: 'Classic Nepali steamed dumplings served with spicy tomato achhar.',
    categoryId: 'cat_food',
    tags: ['momo', 'buff momo', 'dumplings', 'food', 'meals'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_dal_bhat',
    title: 'Authentic Nepali Veg Dal Bhat Set',
    description: 'Traditional meal with steamed rice, lentil soup, seasonal vegetable curry, pickle, and papad.',
    categoryId: 'cat_food',
    tags: ['dal bhat', 'thali', 'lunch', 'dinner', 'food', 'meals'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_tims_card',
    title: 'Trekkers Information Management System (TIMS) Card - Foreigner',
    description: 'Mandatory trekking registration card issued by Nepal Tourism Board.',
    categoryId: 'cat_permits',
    tags: ['tims', 'permit', 'trekking', 'government fee'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_acap_permit',
    title: 'Annapurna Conservation Area Project (ACAP) Entry Permit',
    description: 'Official government conservation area entry permit for Annapurna region.',
    categoryId: 'cat_permits',
    tags: ['permit', 'annapurna', 'acap', 'park entry', 'government fee'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_ncell_sim',
    title: 'Ncell 20GB 14-Day Tourist SIM Pack',
    description: 'Official prepaid tourist SIM card with 20GB high-speed data and local call allowance.',
    categoryId: 'cat_communication',
    tags: ['sim', 'data', 'recharge', 'ncell', 'internet'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_down_jacket_rental',
    title: 'Trekking Down Jacket (-10°C) Rental',
    description: 'High-altitude insulated down jacket rental per day for Everest/Annapurna treks.',
    categoryId: 'cat_trekking',
    tags: ['jacket', 'rental', 'equipment', 'trekking goods', 'sleeping equipment'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_pashmina_shawl',
    title: '100% Cashmere Pashmina Shawl (Water Pashmina Grade)',
    description: 'Authentic handwoven Nepalese cashmere pashmina shawl.',
    categoryId: 'cat_shopping',
    tags: ['clothing', 'pashmina', 'souvenirs', 'handicrafts', 'local products'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_laundry_service',
    title: 'Tourist Laundry Service (per kg)',
    description: 'Wash, dry, and fold laundry service in tourist hubs.',
    categoryId: 'cat_services',
    tags: ['laundry', 'services', 'wash'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_luggage_storage',
    title: 'Luggage Storage Service (per day)',
    description: 'Secure luggage storage in Thamel / Pokhara while trekking.',
    categoryId: 'cat_services',
    tags: ['luggage storage', 'storage', 'services'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_paragliding_flight',
    title: 'Pokhara Paragliding 30-min Tandem Flight',
    description: 'Licensed tandem paragliding flight over Phewa Lake with photo & video included.',
    categoryId: 'cat_activities',
    tags: ['paragliding', 'activities', 'adventure', 'tours'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_teahouse_room',
    title: 'Trekking Teahouse Twin Room (Namche / High Altitude)',
    description: 'Standard teahouse twin bedroom night fee along Everest Base Camp trail.',
    categoryId: 'cat_accommodation',
    tags: ['teahouse', 'lodge', 'hotel fees', 'accommodation', 'hostel'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
];

export const SEED_PRICE_RECORDS: PriceRecord[] = [
  // Wai Wai MRP
  {
    id: 'pr_waiwai_mrp',
    productId: 'prod_wai_wai',
    sourceId: 'src_cg_foods',
    venueId: 'ven_supermarket_thamel',
    price: 20,
    currency: 'NPR',
    unit: 'packet',
    priceType: 'official_mrp',
    observedAt: '2026-08-15T10:00:00Z',
    retrievedAt: '2026-09-01T00:00:00Z',
    sourceUrl: 'https://cgfoods.com/products/wai-wai',
    sourceQuality: 5,
    isActive: true,
    isSeed: true,
    notes: 'Official maximum retail price printed on packaging.',
  },
  // Bottled Water MRP vs Tourist markup
  {
    id: 'pr_water_mrp',
    productId: 'prod_water_1l',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_supermarket_thamel',
    price: 25,
    currency: 'NPR',
    unit: 'bottle',
    priceType: 'official_mrp',
    observedAt: '2026-09-01T09:00:00Z',
    retrievedAt: '2026-09-02T00:00:00Z',
    sourceUrl: 'https://kvta.org.np/market-rates-2026',
    sourceQuality: 5,
    isActive: true,
    isSeed: true,
    notes: 'Standard printed MRP for 1L bottled water in Nepal.',
  },
  {
    id: 'pr_water_namche',
    productId: 'prod_water_1l',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_namche_lodge',
    price: 150,
    currency: 'NPR',
    unit: 'bottle',
    priceType: 'retail',
    observedAt: '2026-09-10T12:00:00Z',
    retrievedAt: '2026-09-12T00:00:00Z',
    sourceQuality: 4,
    isActive: true,
    isSeed: true,
    notes: 'High altitude porter transport surcharge added at 3,440m altitude.',
  },

  // Dal Bhat Local vs Tourist Restaurant (CONFLICT CASE)
  {
    id: 'pr_dalbhat_asan',
    productId: 'prod_dal_bhat',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_asan_eatery',
    price: 250,
    currency: 'NPR',
    unit: 'plate',
    priceType: 'restaurant_menu',
    observedAt: '2026-09-02T12:00:00Z',
    retrievedAt: '2026-09-03T00:00:00Z',
    sourceUrl: 'https://kvta.org.np/market-rates-2026',
    sourceQuality: 4,
    isActive: true,
    isSeed: true,
    notes: 'Authentic local eatery price in Asan Chowk. Unlimited refill.',
  },
  {
    id: 'pr_dalbhat_thamel',
    productId: 'prod_dal_bhat',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_thamel_restaurant',
    price: 650,
    currency: 'NPR',
    unit: 'plate',
    priceType: 'restaurant_menu',
    observedAt: '2026-09-05T19:00:00Z',
    retrievedAt: '2026-09-06T00:00:00Z',
    sourceUrl: 'https://kvta.org.np/market-rates-2026',
    sourceQuality: 4,
    isActive: true,
    isSeed: true,
    notes: 'Tourist restaurant menu rate including 10% service charge.',
  },

  // Buff Momo
  {
    id: 'pr_momo_asan',
    productId: 'prod_buff_momo',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_asan_eatery',
    price: 130,
    currency: 'NPR',
    unit: 'plate',
    priceType: 'restaurant_menu',
    observedAt: '2026-09-02T13:00:00Z',
    retrievedAt: '2026-09-03T00:00:00Z',
    sourceQuality: 4,
    isActive: true,
    isSeed: true,
  },
  {
    id: 'pr_momo_thamel',
    productId: 'prod_buff_momo',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_thamel_restaurant',
    price: 320,
    currency: 'NPR',
    unit: 'plate',
    priceType: 'restaurant_menu',
    observedAt: '2026-09-05T18:00:00Z',
    retrievedAt: '2026-09-06T00:00:00Z',
    sourceQuality: 4,
    isActive: true,
    isSeed: true,
  },

  // TIMS Card & ACAP Permit (Official Gov Tariffs)
  {
    id: 'pr_tims_gov',
    productId: 'prod_tims_card',
    sourceId: 'src_ntb',
    venueId: 'ven_gov_ntb',
    price: 2000,
    currency: 'NPR',
    unit: 'person',
    priceType: 'official_tariff',
    observedAt: '2026-01-01T00:00:00Z',
    retrievedAt: '2026-09-01T00:00:00Z',
    sourceUrl: 'https://timsnepal.com',
    sourceQuality: 5,
    isActive: true,
    isSeed: true,
    notes: 'Official Nepal Tourism Board rate for individual SAARC/Foreign trekkers.',
  },
  {
    id: 'pr_acap_official',
    productId: 'prod_acap_permit',
    sourceId: 'src_dnpwc',
    venueId: 'ven_gov_ntb',
    price: 3000,
    currency: 'NPR',
    unit: 'person',
    priceType: 'official_tariff',
    observedAt: '2026-01-01T00:00:00Z',
    retrievedAt: '2026-09-01T00:00:00Z',
    sourceUrl: 'https://dnpwc.gov.np/en/permits/',
    sourceQuality: 5,
    isActive: true,
    isSeed: true,
  },
  {
    id: 'pr_acap_agency_quote',
    productId: 'prod_acap_permit',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_thamel_restaurant',
    price: 4500,
    currency: 'NPR',
    unit: 'person',
    priceType: 'provider_quote',
    observedAt: '2026-09-10T00:00:00Z',
    retrievedAt: '2026-09-12T00:00:00Z',
    sourceQuality: 3,
    isActive: true,
    isSeed: true,
    notes: 'Travel agency service fee included quote for hassle-free processing.',
  },

  // Ncell Tourist SIM (Official vs Reseller CONFLICT)
  {
    id: 'pr_ncell_official',
    productId: 'prod_ncell_sim',
    sourceId: 'src_ncell',
    venueId: 'ven_tia_prepaid',
    sellerId: 'sel_ncell_official',
    price: 600,
    currency: 'NPR',
    unit: 'pack',
    priceType: 'official_tariff',
    observedAt: '2026-09-10T00:00:00Z',
    retrievedAt: '2026-09-10T00:00:00Z',
    sourceUrl: 'https://www.ncell.axiata.com/en/mobile/tourist-pack',
    sourceQuality: 5,
    isActive: true,
    isSeed: true,
    notes: 'Official airport exit gate counter price with free SIM card insertion.',
  },
  {
    id: 'pr_ncell_reseller',
    productId: 'prod_ncell_sim',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_thamel_restaurant',
    price: 1100,
    currency: 'NPR',
    unit: 'pack',
    priceType: 'retail',
    observedAt: '2026-09-12T00:00:00Z',
    retrievedAt: '2026-09-14T00:00:00Z',
    sourceQuality: 3,
    isActive: true,
    isSeed: true,
    notes: 'Hotel desk reseller package including activation assistance.',
  },

  // Down Jacket Rental
  {
    id: 'pr_jacket_rental',
    productId: 'prod_down_jacket_rental',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_lakeside_gear',
    price: 150,
    currency: 'NPR',
    unit: 'day',
    priceType: 'retail',
    observedAt: '2026-09-08T00:00:00Z',
    retrievedAt: '2026-09-09T00:00:00Z',
    sourceQuality: 4,
    isActive: true,
    isSeed: true,
  },

  // Pashmina Shawl (Marketplace vs Shop)
  {
    id: 'pr_pashmina_shop',
    productId: 'prod_pashmina_shawl',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_thamel_restaurant',
    sellerId: 'sel_thamel_crafts',
    price: 3500,
    currency: 'NPR',
    unit: 'piece',
    priceType: 'retail',
    observedAt: '2026-09-04T00:00:00Z',
    retrievedAt: '2026-09-05T00:00:00Z',
    sourceQuality: 4,
    isActive: true,
    isSeed: true,
  },

  // Services
  {
    id: 'pr_laundry_thamel',
    productId: 'prod_laundry_service',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_thamel_restaurant',
    price: 150,
    currency: 'NPR',
    unit: 'kg',
    priceType: 'retail',
    observedAt: '2026-09-05T00:00:00Z',
    retrievedAt: '2026-09-06T00:00:00Z',
    sourceQuality: 4,
    isActive: true,
    isSeed: true,
  },
  {
    id: 'pr_luggage_thamel',
    productId: 'prod_luggage_storage',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_thamel_restaurant',
    price: 200,
    currency: 'NPR',
    unit: 'day',
    priceType: 'retail',
    observedAt: '2026-09-05T00:00:00Z',
    retrievedAt: '2026-09-06T00:00:00Z',
    sourceQuality: 4,
    isActive: true,
    isSeed: true,
  },

  // Activities (Pokhara Paragliding)
  {
    id: 'pr_paragliding_official',
    productId: 'prod_paragliding_flight',
    sourceId: 'src_nasa_paragliding',
    venueId: 'ven_lakeside_gear',
    sellerId: 'sel_pokhara_tours',
    price: 8500,
    currency: 'NPR',
    unit: 'flight',
    priceType: 'official_tariff',
    observedAt: '2026-09-01T00:00:00Z',
    retrievedAt: '2026-09-01T00:00:00Z',
    sourceUrl: 'https://nepalairportsports.org/rates',
    sourceQuality: 5,
    isActive: true,
    isSeed: true,
    notes: 'Official rate approved by Civil Aviation Authority & NAA.',
  },
  {
    id: 'pr_paragliding_agent',
    productId: 'prod_paragliding_flight',
    sourceId: 'src_pokhara_audit',
    venueId: 'ven_lakeside_gear',
    sellerId: 'sel_pokhara_tours',
    price: 11000,
    currency: 'NPR',
    unit: 'flight',
    priceType: 'provider_quote',
    observedAt: '2026-09-06T00:00:00Z',
    retrievedAt: '2026-09-07T00:00:00Z',
    sourceQuality: 3,
    isActive: true,
    isSeed: true,
    notes: 'Lakeside street agent package including hotel pickup and go-pro video memory card.',
  },

  // Teahouse Twin Room
  {
    id: 'pr_teahouse_namche',
    productId: 'prod_teahouse_room',
    sourceId: 'src_thamel_audit',
    venueId: 'ven_namche_lodge',
    price: 800,
    currency: 'NPR',
    unit: 'night',
    priceType: 'retail',
    observedAt: '2026-09-10T00:00:00Z',
    retrievedAt: '2026-09-12T00:00:00Z',
    sourceQuality: 4,
    isActive: true,
    isSeed: true,
    notes: 'Standard room price subject to ordering meals at the lodge.',
  },
];

export const SEED_TRANSPORT_ROUTES: TransportRoute[] = [
  {
    id: 'route_tia_thamel',
    name: 'Kathmandu Airport (TIA) to Thamel',
    originName: 'Kathmandu Airport (TIA)',
    originLat: 27.6981,
    originLng: 85.3592,
    destinationName: 'Thamel',
    destLat: 27.7154,
    destLng: 85.3123,
    distanceKm: 6.5,
    estimatedDurationMins: 25,
  },
  {
    id: 'route_tia_patan',
    name: 'Kathmandu Airport (TIA) to Patan Durbar Square',
    originName: 'Kathmandu Airport (TIA)',
    originLat: 27.6981,
    originLng: 85.3592,
    destinationName: 'Patan',
    destLat: 27.6744,
    destLng: 85.325,
    distanceKm: 7.2,
    estimatedDurationMins: 30,
  },
  {
    id: 'route_tia_bhaktapur',
    name: 'Kathmandu Airport (TIA) to Bhaktapur Durbar Square',
    originName: 'Kathmandu Airport (TIA)',
    originLat: 27.6981,
    originLng: 85.3592,
    destinationName: 'Bhaktapur',
    destLat: 27.6722,
    destLng: 85.4288,
    distanceKm: 12.4,
    estimatedDurationMins: 35,
  },
  {
    id: 'route_ktm_pokhara',
    name: 'Kathmandu to Pokhara Intercity Journey',
    originName: 'Kathmandu',
    originLat: 27.7315,
    originLng: 85.3125,
    destinationName: 'Pokhara',
    destLat: 28.2045,
    destLng: 83.9782,
    distanceKm: 205.0,
    estimatedDurationMins: 420,
  },
  {
    id: 'route_pkr_sarangkot',
    name: 'Pokhara Lakeside to Sarangkot Viewpoint',
    originName: 'Pokhara Lakeside',
    originLat: 28.2096,
    originLng: 83.9587,
    destinationName: 'Sarangkot',
    destLat: 28.2435,
    destLng: 83.9482,
    distanceKm: 11.2,
    estimatedDurationMins: 30,
  },
  {
    id: 'route_ratnapark_ringroad',
    name: 'Ratna Park City Center to Ring Road Bus Circuit',
    originName: 'Ratna Park',
    originLat: 27.7058,
    originLng: 85.3149,
    destinationName: 'Ring Road',
    destLat: 27.7176,
    destLng: 85.3464,
    distanceKm: 4.8,
    estimatedDurationMins: 20,
  },
];

export const SEED_TRANSPORT_FARES: TransportFare[] = [
  // TIA to Thamel
  {
    id: 'tf_tia_thamel_prepaid',
    routeId: 'route_tia_thamel',
    transportCategory: 'official_taxi',
    fare: 800,
    currency: 'NPR',
    providerName: 'TIA Official Prepaid Taxi Counter',
    sourceId: 'src_caan_tia',
    sourceUrl: 'https://www.kathmanduairport.com.np/prepaid-taxi',
    observedAt: '2026-09-01T00:00:00Z',
    priceType: 'official_tariff',
    rulesNote: 'Official fixed prepaid ticket fare. Standard airport arrival gate rate.',
    trafficContext: 'Heavy traffic expected during peak hours (08:30-10:00, 16:30-18:30). Fare remains fixed NPR 800.',
  },
  {
    id: 'tf_tia_thamel_micro',
    routeId: 'route_tia_thamel',
    transportCategory: 'public_bus',
    fare: 30,
    currency: 'NPR',
    providerName: 'DoTM Local Public Transit',
    sourceId: 'src_dotm',
    sourceUrl: 'https://dotm.gov.np/tariffs',
    observedAt: '2026-09-01T00:00:00Z',
    priceType: 'official_tariff',
    rulesNote: 'Standard local public microbus tariff (Airport Gate to Ratna Park / Jamal).',
  },
  {
    id: 'tf_tia_thamel_provider',
    routeId: 'route_tia_thamel',
    transportCategory: 'private_transfer',
    fare: 1200,
    currency: 'NPR',
    providerName: 'Himalayan Luxury Private Transfer',
    sourceId: 'src_thamel_audit',
    sourceUrl: 'https://kvta.org.np/market-rates-2026',
    observedAt: '2026-09-12T10:00:00Z',
    priceType: 'provider_quote',
    rulesNote: 'Private AC sedan transfer service booked in advance with driver meetup.',
  },

  // TIA to Patan
  {
    id: 'tf_tia_patan_prepaid',
    routeId: 'route_tia_patan',
    transportCategory: 'official_taxi',
    fare: 850,
    currency: 'NPR',
    providerName: 'TIA Official Prepaid Taxi Counter',
    sourceId: 'src_caan_tia',
    sourceUrl: 'https://www.kathmanduairport.com.np/prepaid-taxi',
    observedAt: '2026-09-01T00:00:00Z',
    priceType: 'official_tariff',
    rulesNote: 'Official fixed prepaid ticket fare from TIA to Patan Durbar Square.',
  },

  // KTM to Pokhara
  {
    id: 'tf_ktm_pkr_bus',
    routeId: 'route_ktm_pokhara',
    transportCategory: 'tourist_bus',
    fare: 1200,
    currency: 'NPR',
    providerName: 'Standard Tourist Sofa Bus',
    sourceId: 'src_dotm',
    sourceUrl: 'https://dotm.gov.np/tariffs',
    observedAt: '2026-09-01T00:00:00Z',
    priceType: 'published_operator_fare',
    rulesNote: 'Includes morning departure (07:00 AM) from Sorhakhutte with lunch stop.',
  },
  {
    id: 'tf_ktm_pkr_vip_bus',
    routeId: 'route_ktm_pokhara',
    transportCategory: 'tourist_bus',
    fare: 2500,
    currency: 'NPR',
    providerName: 'VIP Super Deluxe Air-Suspension Bus',
    sourceId: 'src_thamel_audit',
    observedAt: '2026-09-05T00:00:00Z',
    priceType: 'provider_quote',
    rulesNote: 'Includes reclining seats, onboard washroom, meal box, and WiFi.',
  },
  {
    id: 'tf_ktm_pkr_jeep',
    routeId: 'route_ktm_pokhara',
    transportCategory: 'shared_jeep',
    fare: 1500,
    currency: 'NPR',
    providerName: 'Kalanki Shared Scorpio Express',
    sourceId: 'src_dotm',
    sourceUrl: 'https://dotm.gov.np/tariffs',
    observedAt: '2026-09-01T00:00:00Z',
    priceType: 'official_tariff',
    rulesNote: 'Per seat fare in 7-seater Scorpio departing Kalanki.',
  },

  // Pokhara to Sarangkot
  {
    id: 'tf_pkr_sarangkot_taxi',
    routeId: 'route_pkr_sarangkot',
    transportCategory: 'official_taxi',
    fare: 1000,
    currency: 'NPR',
    providerName: 'Pokhara Taxi Association Reference Rate',
    sourceId: 'src_pokhara_audit',
    observedAt: '2026-09-06T00:00:00Z',
    priceType: 'community_reported',
    rulesNote: 'Round-trip sunrise trip with 1 hour waiting time at Sarangkot tower.',
  },

  // Ratna Park to Ring Road
  {
    id: 'tf_city_micro',
    routeId: 'route_ratnapark_ringroad',
    transportCategory: 'public_bus',
    fare: 25,
    currency: 'NPR',
    providerName: 'Kathmandu Valley Public Microbus',
    sourceId: 'src_dotm',
    sourceUrl: 'https://dotm.gov.np/tariffs',
    observedAt: '2026-09-01T00:00:00Z',
    priceType: 'official_tariff',
    rulesNote: 'Standard student/regular distance tier (0-5 km).',
  },
];
